### PR TITLE
Add gamepad support

### PR DESCRIPTION
**Pull request by meghprkh**

### CODE REVIEW

**Comment by meghprkh** [comment]
I split everything into individual commits since as you said "it is easier to merge then split" =)

(This includes splitting the callback delegates)

**Comment by Kekun** [comment]
Great job! :)

I just see two tiny things to fix:
- the last three commits affect the retro module, even though they are related to gamepad support: the shortlog's prefix for these should be `retro` and not `gamepad`;
- the last commit is fixing the issue, hence it should have `Fixes #303` at the end of the message, see existing commit messages if you have doubts.

**Comment by Kekun** [comment]
Actually there are still some things to fix we forgot about, the patch is introducing these compile time warnings:

```
gamepad/gamepad-mappings-manager.vala:39.24-39.47: warning: unhandled error `GLib.IOError'
        var mapping_string = data_stream.read_line ();
                             ^^^^^^^^^^^^^^^^^^^^^^^^
gamepad/gamepad-mappings-manager.vala:42.21-42.44: warning: unhandled error `GLib.IOError'
            mapping_string = data_stream.read_line ();
                             ^^^^^^^^^^^^^^^^^^^^^^^^
gamepad/gamepad-mappings-manager.vala:34.26-34.79: warning: unhandled error `GLib.Error'
        add_from_input_stream (resources_open_stream (path, ResourceLookupFlags.NONE));
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gamepad/gamepad-mappings-manager.vala:19.3-19.70: warning: unhandled error `GLib.IOError'
        add_from_resource ("/org/gnome/Games/gamepads/gamecontrollerdb.txt");
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gamepad/gamepad-mappings-manager.vala:30.26-30.37: warning: unhandled error `GLib.Error'
        add_from_input_stream (file.read ());
                               ^^^^^^^^^^^^
gamepad/gamepad-monitor.vala:43.14-43.38: warning: unhandled error `GLib.FileError'
            gamepad = new Gamepad (raw_gamepad);
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
gamepad/gamepad-mappings-manager.vala:28.2-28.26: warning: method `Games.GamepadMappingsManager.add_from_file' never used
    public void add_from_file (string file_name) throws IOError {
    ^^^^^^^^^^^^^^^^^^^^^^^^^
gamepad/gamepad-mappings-manager.vala:67.2-67.24: warning: method `Games.GamepadMappingsManager.get_name' never used
    public string? get_name (string guid) {
    ^^^^^^^^^^^^^^^^^^^^^^^
```

If you don't know how to fix you patch set without rewritting everything or loosing anything don't hesitate to ask.

**Comment by meghprkh** [comment]
SHould I remove each of the unused functions and add throwing at each of
the the functions?

**Comment by meghprkh** [comment]
Closing with https://github.com/Kekun/gnome-games/commit/74d21695aa23957509ee69e507f3a2bdd92c5045

**Pull request closed without merging**
