### PR TITLE
Show friendly error message when missing plugin

### LINKED ISSUE #167: Useless error when plugin is missing
I didn't have any retro plugins installed and launching a GB game errored out:

```
Couldn't run game: module '
```

### PR DESCRIPTION
**Pull request by meghprkh**
Fix #167

### CODE REVIEW

**Comment by Kekun** [comment]
We try to follow the GNOME commit message rules: https://wiki.gnome.org/Git/CommitMessages

The only difference for the moment is that we replace the link to bugzilla by "Fixes #xxx" and only on the commit really fixing the bug (usually the last one).

**Comment by meghprkh** [comment]
Okay updated the commit

**Comment by Kekun** [comment]
Besides the removed line and the commit message, your patch looks good.

Maybe the original design of RetroRunner wasn't that great: module_path and module_basename are only used in prepare_core() which is only called in the constructor. What about getting rid of the module_path attribute first and passing the module_basename to prepare_core() as a param?

It would need a new refactoring bug entry from which #167 would depend.

What do you think?

**Comment by meghprkh** [comment]
Yes that would be better

**Comment by Kekun** [comment]
> Show friendly error message when missing plugin
> 
> Currently the error message shown when a plugin is missing is useless. This
> commit shows the user a better error message.

We have to prefix the short message by the affected module when there is one, here it would be retro-runner.

The message says how the change affect the user but not what the change actually do to the code base, what about:

> retro-runner: Add module basename in 'not found' error msg
> 
> Replace the module path by its basename in the error message when no
> module was found for the given path.
> 
> This avoids to have a poorly formated error message when the module path
> is empty.

Here the short message is too long but it's not that big of a deal as it needs to be concise, understandable yet useful while stating what the commit changes an where.

**Pull request closed without merging**
