### PR TITLE
Feature/desktop games listing

### PR DESCRIPTION
**Pull request by sebn**
To Do:
- [x] Keep packages in alphabetical order in both `configure.ac` and `Makefile.am`
- [x] Stick to vala code style
- [ ] ~~Extract some iterable `GameCollection` class from `GameSource`~~
- [x] Show icons
- [x] Inject services into AppWindow
- [x] Code smell: private method: `DesktopGameSource.build_desktop_game()`
- [x] Rename `each_game` to `@foreach`
- [x] Only one code-style commit
- [x] Extract `ui/application.vala#Games.Application` from main
- [x] Move dependency injection commit up (in order not to remove previously added code)

### CODE REVIEW

**Comment by Kekun** [comment]
I'm going to be a bit nitpicking, but globally this PR looks good to me. =)

core: Introduce GameSource interface:
What about `Games.GameSource.@foreach(Func<Game> func)` instead of `Games.GameSource.each_game(GameCallback callback)`? It would be consistent with GLib.List and remove the need for adding GameCallback.

build: Add tracker-sparql dependency:
Please keep packages in alphabetical order in the Makefile too.

desktop: Introduce DesktopGameSource:
Nice! =) What about changing slightly its constructor to the following? This way the next commit would need one line less and we woudl have a sane default.

``` vala
public DesktopGameSource (Tracker.Sparql.Connection tracker = Tracker.Sparql.Connection.@get ())
```

**Comment by sebn** [comment]
> What about Games.GameSource.@foreach(Func<Game> func)

There is another issue for this, and it wasn't introduced in this branch (the API is identical), so I was expecting it to be refactored in another branch/PR.
Anyway, let's fix this right now.

> Please keep packages in alphabetical order in the Makefile too.

I didn't notice this was the order you use. Will fix it too.

> public DesktopGameSource (Tracker.Sparql.Connection tracker = Tracker.Sparql.Connection.@get ())

I was still looking at the right way to inject dependencies (see to-do's in PR description).
The app window is definitely not the right place to instanciate the tracker connection.
Your solution would work, and be testable.
But wouldn't passing it as default in the constructor have some disadvantages ? Namely:
- In case we need a tracker connection somewhere else, we would have to create another one, while one connection may be sufficient (actually I'm not sure whether `@get` is a singleton method, of whether it instanciates a new one on each call, doc doesn't help me so much, will investigate this)
- I'm not sure when default parameters are evaluated, wouldn't the connection be created while the constructor hasn't be called yet?

**Comment by sebn** [comment]
Do we really need an iterable collection right now?
This would require adding 30 lines of code:
https://wiki.gnome.org/Projects/Vala/GeeSamples#Implementing_your_own_Iterable
And current code seems already easy to understand and maintain...
WDYT?

**Comment by sebn** [comment]
I think we should stick to `GameCallback`.
As soon as we identify some collection-related behavior, we can emerge some class, and make it a good vala citizen (i.e. make it iterable).
But right now, with our current needs, the callback design looks good to me.

**Comment by sebn** [comment]
Also, I'd like to rename `main.vala#Games.GnomeGames` to `ui/application.vala#Games.Application`, since it depends on `Gtk`.
WDYT?

**Comment by Kekun** [comment]
## Iterable

Yes I'm not sure we need it to be iterable, I would say let's just stick to GLib.List's syntax and semantics. =) Especially as making a class iterable requires to use an external library (WTF? That should be a feature of the language!).

I would still call the method `@foreach()` rather than `each_game()`, `each_games()` sound more like you'll get each games, while `@foreach()` is more clear on the fact that you are just doing some operation for each element. What do you think?

## GameCallback

I'm not sure GameCallback is needed as it's exactly the same as Func<Game>, but longer to write, adding one line of code and not adding more semantics. But in the end I don't really care on that point, do as you prefer. =)

## About "app,ui: inject dependencies into AppWindow":

Please do that earlier in the PR so you don't add code to remove it later in the same PR.

## Code style fixing

I'm not sure this:

```
- public void loadGameList() {
+ public void loadGameList(GameSource game_source) {
```

followed by this:

```
- public void loadGameList(GameSource game_source) {
+ public void loadGameList (GameSource game_source) {
```

makes much sense, if you consider modifying a line the same a removing one and adding one, you are adding a coding style error to fix it in the next commit. For such cases I would say just add the space in the first commit, it's make the repository lighter. Are you OK with that?

## Moving the application's code

I'm OK with that. =)

## Desktop directory

A thing I forgot to say last time, I'm not sure having a desktop directory is a good idea, maybe we should have one for game sources, one for game types... something like that:

```
games/desktop-game.vala
games/retro-game.vala
sources/desktop-game-source.vala
sources/retro-game-source.vala
```

rather than:

```
desktop/desktop-game.vala
desktop/desktop-game-source.vala
retro/retro-game.vala
retro/retro-game-source.vala
```

What do you think?

**Comment by sebn** [comment]
> I'm not sure having a desktop directory is a good idea

I tend to stick to some desktop-dir-like architecture for my projects, because:
- I can list all supported platforms by looking as the subdirs list
- I can list all features supported by some platform by looking at the subdir content
- It makes moving to some plugin architecture easier (just make each subdir a plugin)
- It tends to group code around common dependencies (means when desktop entry spec changes, we only rebuild the desktop subdir)
- It tend to group code by maintainers (means the megadrive maintainer sees most of his code in a single subdir, without being overwhelmed with snes or steam files he doesn't care)
- It still makes it possible to see all sources/types since we have to register all of them somewhere in the code anyway

**Comment by sebn** [comment]
? I would still call the method @foreach() rather than each_game()

Yeah, `each_game` is very "rubyish", not "valaish".
I don't really like `foreach` either, no underscore, and using a keyword in the method name feels a bit strange...
What about `with_each_game` ?

**Comment by Kekun** [comment]
Yep it makes sense, I'm OK with this directory architecture then. =)

I'm not fond of `with_each_game()` either... I really think we should really work with the customs of GLib and Gtk and use either `@foreach()` or `forall()` (I tend to prefer `@foreach()`).

**Comment by Kekun** [comment]
Remember we may not be the only two working on it in the future, sticking to GLib customs would help GNOME devs feel at home.

**Comment by sebn** [comment]
>  I really think we should really work with the customs of GLib 

Oh, sorry, my bad, I didn't know the `@foreach` naming syntax, so I didn't understand.
`@foreach` sounds fine.

> I'm not sure GameCallback is needed as it's exactly the same as Func

Not exactly, since it takes a `Game` as an argument, so it seemed useful to me to make it explicit.
Or am I missing something regarding callbacks (as with the `@foreach` syntax) ? :)

> For such cases I would say just add the space in the first commit, it's make the repository lighter. Are you OK with that?

If we look at the global diff, it changes nothing.
And if we look at each commit individually, it doesn't mix feature-related changes with code-style ones.
But I agree we could have only one code-style fixing commit. Agreed?

> Please do that earlier in the PR so you don't add code to remove it later in the same PR.

Nice catch.

**Comment by sebn** [comment]
Of course, best would be not to have any code-style commits :)

**Comment by Kekun** [comment]
> Oh, sorry, my bad, I didn't know the @foreach naming syntax, so I didn't understand.
> @foreach sounds fine.

I like it when a big set of code share the same style (I'm talking about our project and the GNOME frameworks), it makes it more consistent and help to share code and knowledge. =)

> Or am I missing something regarding callbacks (as with the @foreach syntax) ? :)

Nah, you may be right here, lets use the delegate you defined. =)

> If we look at the global diff, it changes nothing.
> And if we look at each commit individually, it doesn't mix feature-related changes with code-style ones.
> But I agree we could have only one code-style fixing commit. Agreed?

I admit this one was mostly nitpicking, do as you think is the best. ^^

> Of course, best would be not to have any code-style commits :)

Of course. =p

**Comment by sebn** [comment]
GitHub shows commits in the wrong order, not sure why...

**Comment by sebn** [comment]
Looking at the current code, I'm not sure anymore `@foreach` is a good name.
It would be a good one for a collection type, but `GameSource` is not really a collection.
So I think `@foreach` is actually misleading.
I'd like to get back to `each_game`.
I don't think it's such a bad name, there is even an `each`-style example on GNOME wiki:
https://wiki.gnome.org/Projects/Vala/GeeSamples#line-226

**Comment by sebn** [comment]
:shipit:

**Comment by Kekun** [comment]
## app,ui: inject dependencies into AppWindow

In the log you talk about instantiating the Tracker connection when what you really instantiate is the GameSource. The code is good but the log should be rephrased.

## core: Introduce GameSource interface

No @foreach() then ?

Good otherwise.

## build: Add tracker-sparql dependency

ack

## build: add gio-unix-2.0 dependency

ack

## desktop: Introduce DesktopGameSource

If we are going to  add empty lines between modules in the makefile, please add one between desktop/desktop-game-source.vala and ui/app-window.vala.

## ui: Use DesktopGameSource instead of DummyGameSource

ack

## core: Remove DummyGameSource

ack

## all: Fix code style

Some files use spaces, other files tabs use tabs, lets make it consistent! And more importantly, it looks like a different issue from the one we're trying to solve here. Lets fix that in a different ticket.

## app,ui: Extract Games.Application from main

The new line in the makefile should have been added earlier, other than that, ack.

## core,desktop: Game now takes an icon

`Icon icon` should be of type `Icon? icon` and shouldn't be set by game. It should only be set by classes which need it such as DesktopGame.

You may want to introduce the DesktopGame class first to fix this. =)

`Icon? icon` could even be virtual so DesktopGame could reimplement its getter and just return it's entry's icon when needed.

## ui: Show game icons in list

ack

**Comment by Kekun** [comment]
Also, please be consistent with capitals in the shortlogs, the right part of a shortlog should start by a capital.

**Comment by sebn** [comment]
> https://github.com/sebn/gnome-games/pull/15

Fixed

> No @foreach() then ?

I would say no.

> empty lines between modules in the makefile

Fixed

> Some files use spaces, other files tabs use tabs

Will fix this for changed code

> You may want to introduce the DesktopGame class first to fix this.

I don't agree.
Right now we have no good reason to have 2 games class behaving differently.
We are listing games and displaying their icons, and that's all.
We should not anticipate on future features, let's keep it atomic.

**Comment by sebn** [comment]
> please be consistent with capitals in the shortlog

Fixed

**Comment by Kekun** [comment]
> I don't agree.
> Right now we have no good reason to have 2 games class behaving differently.
> We are listing games and displaying their icons, and that's all.
> We should not anticipate on future features, let's keep it atomic.

Then if we only have on type of games which are desktop games, why don't we treat them as search and create them from a desktop entry rather that from an icon? Actually the real constructor of the game is in the DesktopSource class.

We should either have a Game interface and a concrete DesktopGame class set from a desktop entry, or a single concrete Game class which should act as the only game type we know, desktop games, and be constructed from a desktop entry too.

How it is currently done feels like an incomfortable in between way, neither really abstract, nor really concrete, and it feels kinda bastard in the end.

I would say lets construct the Game class from a desktop entry, we could then later rename it as DesktopGame when we extract the game interface out of it if needed.

WDYT?

**Comment by sebn** [comment]
> We should either have a Game interface and a concrete DesktopGame class set from a desktop entry, or a single concrete Game class

I think the main question (and the reason why we disagree) is whether or not it's ok to have some core model entity (`Game`, or some new `DesktopGame` subclass) depend on `DesktopAppInfo`.

I was feeling bad about this because I didn't know when it parses the file, and I didn't like the idea of calling `game.name` and having it performing some I/O.
Neither did I like the idea of having 100 open files when we list 100 games...
I choose to make `DesktopGameSource` perform the whole "parsing", and return "completed" games.
So, once retrieved, `DesktopGame` are no different from other games, so the concrete `Game` class was sufficient.

But I understand your concern.
Looking at the `DesktopAppInfo` source, it seems the parsing is done at instanciation time, so it would probably be ok to pass the `DesktopAppInfo` to some `DesktopGame` subclass.

**Comment by sebn** [comment]
(still thinking about it)

**Comment by sebn** [comment]
> We should not anticipate on future features, let's keep it atomic.

Actually, I didn't even follow my own advice, since I already introduced some `GameSource` interface, while we now have only one type of game and game source :smile:

**Comment by Kekun** [comment]
Can you connect to IRC?

**Comment by Kekun** [comment]
IMHO the most important reason to not have only one game class in the long run in that each game type will need to be run in its own way, letting us in the need to discriminate them; having subtypes seems to me the easiest way to do so.

Of course, I'm looking in the future which is something we want to do very cautiously, but you get the idea. =)

**Comment by sebn** [comment]
> each game type will need to be run in its own way

That's right, but `Game` is an entity, while "running a game" is a service, so I still feel bad about having `Game` having some `run ()` method.
And if it doesn't have a `run ()` method, and the only difference between game types is their construction, then there is not point anymore in having `Game` subclasses...

**Comment by Kekun** [comment]
Yeah of course! But that's not what I meant. =)

What I meat is that in the long run we probably don't want something like that:

```
DesktopGameRunner (Game game);
run ();
```

but rather that:

```
DesktopGameRunner (DesktopGame game);
run ();
```

and hence we will need to have classes subclassing/implementing Game.

**Comment by sebn** [comment]
Ok, I was thinking of having some `Platform` value object (with some id + human-readable name).
Both `Game` and `GameRunner` would know their `Platform`.
Some `GameRunner` registry or collection would be in charge of retrieving the appropriate runner for a game, and the `GameRunner` would provide the `run ()` method.
So, entities and services would be kept separate.
And `Game` would not have a `run ()` method, with potential injection of some `GameRunner` service in the constructor only required for this same `run ()` method, and depending on infrastructure details...
And I think it's simpler having a single `Game` class depending on an additional `Platform` one, than having a whole tree of `Game` subclasses for the sole purpose of distinguishing their platform.

**Comment by sebn** [comment]
Ideally, `Game` should only deal with game state management.
For example, it may provide some `started_playing ()` and `stopped_playing ()` methods that would be called by the `GameRunner`, and update some `playing` (bool) and `play_duration` properties accordingly.
As the project grows, it may have more state management responsibilities, and we will be happy not to have code cluttered with service-related ones.

**Comment by sebn** [comment]
Your proposal brings some issues.

## Unrequired/unclear constraints

The assumption that 1 platform <=> 1 game source <=> 1 game runner doesn't reflect reality.
Tracker, my  `~/Games` directory, my Steam games library... those are game sources, which may provide games from mutliple platforms.
Libretro, explicit Zsnes invocation, `xdg-open` + mimetype, using the `Exec` line from some desktop entry... Those are different strategies to run games, possibly from multiple platforms too.
And we don't even need a `Steam` runner.

## Grouping objects with differente lifecycles

We won't be using the same technologies for game sources and game runners.
We should not risk to break games retrieval while updating to the latest libretro API for example.
So those should be clearly separate concepts.

## Coupling / unclear responsibilities

The injection of the `GameRunner` into the `Game`s would have to be done by the `GameSource`. But the `GameSource` should know nothing about running games IMHO.

Game sources should only deal with games retrieval, while game runners should only know whether they can run a game from some given platform, and how.

## Bad inheritance

Having every concrete `*GameRunner` class depend on the corresponding concrete `*Game` one  violates the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle).
We should be able to pass any type of game to any type of runner, and have some sane behavior.

## Alternative solution

Since "platform" is a domain concept, it's ok to have a corresponding class, and use it to discriminate games.
So `GameSource`s would provide games with some `platform` property, and `GameRunner` could use it to decide whether they want to run it or not.

This also means less classes, and smaller ones, which is a good design quality metric.

**Comment by Kekun** [comment]
## Coupling and substitution

What do you think of such a design (focusing only on the games and their runners):

```
// Runners

interface Runner : Object {
    void run ();
    void stop ();
}

abstract class ExternalRunner : Object, Game {
    // Runners which can't be tighly coupled to the application
    string exec;
}

abstract class IntegratedRunner : Object, Game {
    // Runners which can be tighly coupled to the application
    // (it can render their video and audio, feed them controls, it can pause it...)
    Display get_display ();
    ...
}

class RetroRunner : IntegratedRunner {
    string uri;
    string core;
}

class WebRunner : IntegratedRunner {
    string url;
}

// Games

interface Game : Object {
    string title;
    Icon icon;
    ...
    Runner get_runner (); // factory method
}

class DesktopGame : Object, Game {
    Entry entry;
    Runner get_runner () {
        return new ExternalRunner (entry.exec);
    }
}

class SnesGame : Object, Game {
    string uri;
    Runner get_runner () {
        return new RetroRunner ("/path/to/snes/core", uri);
    }
}

class MegaDriveGame : Object, Game {
    string uri;
    Runner get_runner () {
        return new RetroRunner ("/path/to/megadrive/core", uri);
    }
}

class WebGame : Object, Game {
    string url;
    Runner get_runner () {
        return new WebRunner (url);
    }
}
```

The application would then handle a collection of games and the runner(s) of the currently running game(s).

I'm not even sure we need the "SnesGame" and "MegaDriveGame" classes if we have a good game factory.

**Comment by sebn** [comment]
Now the game is coupled to the runner.
I should be able to list games without running them.

**Comment by Kekun** [comment]
Instead of having the `Game.get_runner()` method we could have this:

```
class RunnerFactory : Object {
    public Runner create_runner (Game game) throws Error;
        if (game is DesktopGame)
            return create_desktop_runner (game as DesktopGame);
        if (game is SnesGame)
            return create_snes_runner (game as SnesGame);
        if (game is MegaDriveGame)
            return create_mega_drive_runner (game as MegaDriveGame);
        if (game is WebRunner)
            return create_web_runner (game as WebGame);
        throw new Error.UNKNOWN_GAME_TYPE ("Unhandled game: unkown game type");
    }

    public SnesRunner create_desktop_runner (DesktopGame game) throws Error;
        return new ExternalRunner (entry.exec);
    }

    public SnesRunner create_snes_runner (SnesGame game) throws Error;
        return new RetroRunner ("/path/to/snes/core", game.uri);
    }

    public SnesRunner create_mega_drive_runner (MegaDriveGame game) throws Error;
        return new RetroRunner ("/path/to/megadrive/core", game.uri);
    }

    public SnesRunner create_web_runner (WebGame game) throws Error;
        return new WebRunner (game.uri);
    }
}
```

But it feels less robust as errors could be thrown, not every type is certainly handled and all the knowledge concerning Runner creation is centralized in this class. =/

**Comment by Kekun** [comment]
Could you show me how you see the design, by drafting the interfaces as I did? It would help me to grasp what you have in mind. =)

**Comment by sebn** [comment]
I don't really want to continue this way and anticipate on the future design.
Up-front domain design is a bad practice (I'm just talking about the model design, it's ok to agree on broader architecture conventions like MVC for example).
Dreamed objects tend to become actual nightmares.
And believing that it will free us of refactoring is nonsense, better refactor progressively than commiting too much on the wrong way right from the beginning.
We are not releasing a stable application yet, so we should not be afraid of future refactoring.

I'm ok to simplify current design to only 1 `DesktopGameSource` class, and 1 `Game` class, with no interfaces, since we don't need them right now.
Lets wait for next features to let other classes/interfaces emerge as needed.

**Comment by sebn** [comment]
We can discuss again of the best way to design the game running model when we get to implement the corresponding feature.
Doing it right now is just a waste of time imho.

**Comment by Kekun** [comment]
Agreed.

**Comment by Kekun** [comment]
Sorry I implemented it in my own way in the end... its not really fair play from me... but I still did it and this PR can be closed now.

**Comment by sebn** [comment]
No need to apologize.
Better working than not.

**Pull request closed without merging**
